### ISSUE TITLE
Can't load the program!

### ISSUE THREAD

**Issue by 12354fdw** [DylanCope/Evolving-Protozoa#15]
I got the error:

Could not load FiraCode-Retina font
Exception in thread "main" java.lang.RuntimeException: Particle image not found: resources/thumbnail.png
javax.imageio.IIOException: Can't read input file!
	at protoevo.ui.main.MainScreenRenderer.<init>(MainScreenRenderer.java:62)
)
	at protoevo.ui.main.MainScreenRenderer.main(MainScreenRenderer.java:38)

Notes:

I was running the command on my terminal:

java -jar /Users/Bob/Desktop/v0.1.4/Evolving-Protozoa.jar -Xmx8G -Dsun.java2d.opengl=true

And my OS is MacOS Mojave (10.14.6)

**Comment by DylanCope** [comment]
What directory are you running from? I don't have a Mac but it seems like it cannot find the local resource files

**Comment by 12354fdw** [comment]
I was running the command on Users/bob

**Comment by 12354fdw** [comment]
nvm i found out the problem i need to run on Users/bob/Desktop/v1.4.0
