### ISSUE TITLE
Game Freezes on white screen at launch

### ISSUE THREAD

**Issue by RipperPond** [DylanCope/Evolving-Protozoa#17]
Running Java 17, on Mac, I executed it from the terminal, and from the jar file.

**Comment by RipperPond** [comment]
also the terminal has this bit of text after it
Could not load FiraCode-Retina font
Exception in thread "main" java.lang.RuntimeException: Particle image not found: resources/thumbnail.png
javax.imageio.IIOException: Can't read input file!
	at protoevo.ui.main.MainScreenRenderer.<init>(MainScreenRenderer.java:62)
	at protoevo.ui.main.MainScreenRenderer.main(MainScreenRenderer.java:38)
